[package]
name = "app-store-server-library"
description = "The Rust server library for the App Store Server API and App Store Server Notifications"
version = "0.9.1"
repository = "https://github.com/namecare/app-store-server-library-rust"
homepage = "https://github.com/namecare/app-store-server-library-rust"
authors = ["tkhp", "namecare"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/app-store-server-library"
keywords = ["apple", "appstore"]
edition = "2021"

[dependencies]

# Cryptography
x509-parser = { version = "0.15.1", features = ["verify", "validate"] }
jsonwebtoken = { version = "9.2.0" }
ring = "0.17.7"
pem = "3.0.3"

# Serialization
serde = { version = "1.0.195", features = ["derive"] }
serde_json = { version = "1.0.111" }
serde_with = { version = "3.5.0", features = ["chrono"] }
serde_repr = "0.1.18"
uuid = { version = "1.7.0", features = ["serde", "v4"] }
chrono = { version = "0.4.32", features = ["serde"] }
base64 = "0.21.7"
asn1-rs = { version = "0.5.2", optional = true }

# Utils
thiserror = "1.0.56"

# Tools
regex = { version = "1.10.3", optional = true }

[features]
receipt_utility = ["dep:asn1-rs", "dep:regex"]
