[package]
name = "app-store-server-library"
description = "The Rust server library for the App Store Server API and App Store Server Notifications"
version = "0.3.0"
repository = "https://github.com/namecare/app-store-server-library-rust"
homepage = "https://github.com/namecare/app-store-server-library-rust"
authors = ["tkhp", "namecare"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/app-store-server-library"
keywords = ["apple", "appstore"]
edition = "2021"

[dependencies]

# Cryptography
openssl = { version = "0.10.55", features = ["vendored"]}

# Serialization
serde = { version = "1.0.176", features = ["derive"] }
serde_json = { version = "1.0.104" }
serde_with = { version = "3.1.0", features = ["chrono"] }
uuid = { version = "1.4.1", features = ["serde", "v4"] }
chrono = { version = "0.4.26", features = ["serde"] }
base64 = "0.21.2"

# Utils
thiserror = "1.0.44"

[dev-dependencies]
dotenv = "0.15.0"
jsonwebtoken = "8.3.0"
