[package]
name = "app-store-server-library"
description = "The Rust server library for the App Store Server API and App Store Server Notifications"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
authors = ["tkhp", "namecare"]
repository = "https://github.com/namecare/app-store-server-library-rust"
homepage = "https://github.com/namecare/app-store-server-library-rust"

[dependencies]

# Cryptography
openssl = { version = "0.10.55", features = ["vendored"]}
rustls = { version = "0.21.5" }

# Serialization
serde = { version = "1.0.176", features = ["derive"] }
serde_json = { version = "1.0.104" }
serde_with = { version = "3.1.0", features = ["chrono"] }
uuid = { version = "1.4.0", features = ["serde", "v4"] }
chrono = { version = "0.4.26", features = ["serde"] }
base64 = "0.21.2"

[dev-dependencies]
dotenv = "0.15.0"
jsonwebtoken = "8.3.0"
