[package]
name = "app-store-server-library"
description = "The Rust server library for the App Store Server API and App Store Server Notifications"
version = "2.0.0"
repository = "https://github.com/namecare/app-store-server-library-rust"
homepage = "https://github.com/namecare/app-store-server-library-rust"
authors = ["tkhp", "namecare"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/app-store-server-library"
keywords = ["apple", "appstore"]
edition = "2021"

[dependencies]

# Cryptography
x509-parser = { version = "0.16.0", features = ["verify", "validate"] }
jsonwebtoken = { version = "9.3.0" }
ring = "0.17.8"
pem = "3.0.3"

# Serialization
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.115" }
serde_with = { version = "3.7.0", features = ["chrono"] }
serde_repr = "0.1.18"
uuid = { version = "1.8.0", features = ["serde", "v4"] }
chrono = { version = "0.4.37", features = ["serde"] }
base64 = "0.22.0"
asn1-rs = { version = "0.6.1", optional = true }

# Networking
reqwest = { version = "0.12.2", features = ["json"], optional = true }

# Utils
thiserror = "1.0.58"

# Tools
regex = { version = "1.10.4", optional = true }
url = "2.5.0"


[dev-dependencies]
http = "1.1.0"
tokio = { version = "1.37.0", features = ["test-util", "macros"] }
jsonwebtoken = { version = "9.3.0", features = ["use_pem"] }

[features]
api-client = ["dep:reqwest"]
receipt-utility = ["dep:asn1-rs", "dep:regex"]

